/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Perpustakaan extends javax.swing.JFrame {

    private void clearForm(){
        fieldWriterName.setEditable(true);
        fieldWriterName.setText(null);
        fieldTitleBook.setText(null);
        fieldReleaseYear.setText(null);
        fieldPublisher.setText(null);
    }
    
    private void showTable(){
       DefaultTableModel model = new DefaultTableModel();
       model.addColumn("No");
       model.addColumn("Nama Penulis");
       model.addColumn("Judul Buku");
       model.addColumn("Tahun Terbit");
       model.addColumn("Penerbit");
       
     
      
       
       try{
           int no = 1;
           String sql= "SELECT * FROM data_buku ";
           java.sql.Connection connect= (Connection)Config.configDB();
           java.sql.Statement stm = connect.createStatement();
           java.sql.ResultSet res = stm.executeQuery(sql);
           
           while(res.next()){
               model.addRow(new Object[] {no++, res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
           }
           tblBookData.setModel(model);
       } catch(SQLException err){
           System.out.println("Error: "+ err.getMessage());
       }
    }
    /**
     * Creates new form Perpustakaan
     */
    public Perpustakaan() {
        initComponents();
        showTable();
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldWriterName = new javax.swing.JTextField();
        fieldTitleBook = new javax.swing.JTextField();
        fieldReleaseYear = new javax.swing.JTextField();
        fieldPublisher = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookData = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DATA BUKU PEPUSTAKAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 35, -1, -1));

        jLabel2.setText("Nama Penulis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 94, -1, -1));

        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 134, -1, -1));

        jLabel4.setText("Penerbit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 214, -1, -1));

        jLabel5.setText("Tahun Terbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 174, -1, -1));

        fieldWriterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWriterNameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldWriterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 91, 282, -1));
        getContentPane().add(fieldTitleBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 131, 282, -1));
        getContentPane().add(fieldReleaseYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 171, 282, -1));
        getContentPane().add(fieldPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 211, 282, -1));

        tblBookData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBookData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBookData);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 166));

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldWriterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWriterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWriterNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         try{
            String deleteSQL="DELETE FROM data_buku WHERE nama_penulis='"+fieldWriterName.getText()+"'";
            java.sql.Connection connect =(Connection)Config.configDB();
            java.sql.PreparedStatement preparedStatement = connect.prepareStatement(deleteSQL);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Succesfully Delete Data...");
        }catch (HeadlessException | SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }   
         showTable();
         clearForm();     
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String insertSQL="INSERT INTO data_buku(nama_penulis, penerbit, tahun_terbit, judul_buku) VALUES ('"+fieldWriterName.getText()+"','"+fieldPublisher.getText()+"','"+fieldReleaseYear.getText()+"','"+fieldTitleBook.getText()+"')";
            java.sql.Connection connect =(Connection)Config.configDB();
            java.sql.PreparedStatement preparedStatement = connect.prepareStatement(insertSQL);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Succesfully Save Data...");
            showTable();
            clearForm();
        }catch (HeadlessException | SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblBookDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookDataMouseClicked
        // TODO add your handling code here:
        int row = tblBookData.rowAtPoint(evt.getPoint());
        String writerName = tblBookData.getValueAt(row,1).toString();
        fieldWriterName.setText(writerName);
        
        String publisher = tblBookData.getValueAt(row,4).toString();
        fieldPublisher.setText(publisher);
        
        String releaseYear = tblBookData.getValueAt(row,3).toString();
        fieldReleaseYear.setText(releaseYear);
        
        String titleBook = tblBookData.getValueAt(row,2).toString();
        fieldTitleBook.setText(titleBook);
        
        
        
       
    }//GEN-LAST:event_tblBookDataMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
            String updateSQL="UPDATE data_buku SET nama_penulis='"+fieldWriterName.getText()+"',penerbit='"+fieldPublisher.getText()+"',tahun_terbit='"+fieldReleaseYear.getText()+"',judul_buku='"+fieldTitleBook.getText()+"' WHERE nama_penulis='"+fieldWriterName.getText()+"'";
            java.sql.Connection connect =(Connection)Config.configDB();
            java.sql.PreparedStatement preparedStatement = connect.prepareStatement(updateSQL);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Succesfully Edit Data...");
        }catch (HeadlessException | SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }   
         showTable();
         clearForm();                             
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldPublisher;
    private javax.swing.JTextField fieldReleaseYear;
    private javax.swing.JTextField fieldTitleBook;
    private javax.swing.JTextField fieldWriterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblBookData;
    // End of variables declaration//GEN-END:variables
}
